---
title: "Transitioning from the desktop to cloud computing for teaching"
author:
    - Carl Boettiger
    - Ben Bolker
    - Julien Brun (brun@nceas.ucsb.edu)
    - Lauren Hallett
    - Matthew B. Jones (jones@nceas.ucsb.edu)
    - Mark Schildhauer (schild@nceas.ucsb.edu)
    - Mike Smorul
    - Tracy Teal
    - Ethan White
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
  html_document: default
bibliography: references.bib
fontsize: 12
---
<!--
[Original working notes](http://notes.nceas.ucsb.edu/p/ds-workshop-2015-b6-cloud)
[Original Google Doc file](https://docs.google.com/document/d/1Ae-eqRbIn6A-OyZs_oVCgwZlIvvP0o2U7FtonpECVyk/edit)
-->

<!--
Audience:
- Not CS
- domain scientist
- folks looking for a roadmap
- Journals: 
- Transitioning from desktop to scalable computing
-->

```{r child = 'abstract.Rmd'}
```

```{r child = 'introduction.Rmd'}
```

```{r child = 'stage1.Rmd'}
```

```{r child = 'stage2.Rmd'}
```

```{r child = 'stage3.Rmd'}
```

```{r child = 'stage4.Rmd'}
```

```{r child = 'conclusion.Rmd'}
```

```{r child = 'boxes.Rmd'}
```

References
----------
