##  Stage 2: Teaching the cloud (basic)

This an intermediate stage; target audience includes (i) trainers who want to teach in the cloud; (ii) researchers who want to do *basic* scalable computing.

### Advantages

* independence/self-support
* easy scaling for simple problems, lab-level scaling
* farewell to sticky notes
* leave GUI or batch job running on the instance

### Disadvantages

* Cost
* Moving data to/from these resources 
* Figuring out how it works

### Examples
point to DC “how to spin up your own instance” lesson (not taught) https://github.com/JasonJWilliamsNY/cloud-genomics/blob/master/lessons/1.logging-onto-cloud.md (still needs updating)
Titus Brown’s short courses http://angus.readthedocs.org/en/2014/day1.html
iPlant atmosphere
EDAMAME course https://github.com/edamame-course/2015-tutorials/blob/master/final/2015-06-22-EC2_Startup.md, https://github.com/edamame-course/2015-tutorials/blob/master/final/2015-06-22-EC2_Connection_FileTransfer.md

### Learning Objectives

- Standup own images
- the concept of on-demand resources (dynamic nature of cloud resources cpu/memory)
- Understand how to locate and acquire remote resources - local and public cloud
- understand pricing / cost tradeoffs
